-- 1. Criação da Tabela CLIENTE
CREATE TABLE IF NOT EXISTS CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CIDADE VARCHAR(50) NOT NULL
);

-- 2. Criação da Tabela VEICULOS
CREATE TABLE IF NOT EXISTS VEICULOS (
    ID_VEICULOS INT AUTO_INCREMENT PRIMARY KEY,
    NOME_VEICULO VARCHAR(50) NOT NULL,
    PLACA VARCHAR(10) NOT NULL UNIQUE,
    CATEGORIA VARCHAR(30) NOT NULL,
    VALOR_DIARIA DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'disponivel'
);

-- 3. Criação da Tabela ALUGA
CREATE TABLE IF NOT EXISTS ALUGA (
    ID_LOCACAO INT AUTO_INCREMENT PRIMARY KEY,
    FK_CLIENTE_ID_CLIENTE INT NOT NULL,
    FK_VEICULOS_ID_VEICULOS INT NOT NULL,
    DATA_RETIRADA DATE NOT NULL,
    DATA_PREVISTA DATE NOT NULL,
    DATA_DEVOLUCAO DATE NULL,
    DIAS_CONTRATADOS INT NOT NULL,
    DIAS_REAIS INT NULL,
    VALOR_BRUTO DECIMAL(10,2) NOT NULL,
    DESCONTO DECIMAL(10,2) DEFAULT 0.00,
    MULTA DECIMAL(10,2) DEFAULT 0.00,
    VALOR_FINAL DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(30) DEFAULT 'Em andamento',
    
    FOREIGN KEY (FK_CLIENTE_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
    FOREIGN KEY (FK_VEICULOS_ID_VEICULOS) REFERENCES VEICULOS (ID_VEICULOS)
);

-- 4. INSERIR DADOS DE TESTE
INSERT INTO CLIENTE (NOME, DATA_NASCIMENTO, CIDADE) VALUES 
('João Silva', '1994-05-15', 'Curitiba'),
('Ana Souza', '1999-08-22', 'Araucária'),
('Carlos Lima', '1981-11-03', 'Curitiba');

INSERT INTO VEICULOS (NOME_VEICULO, PLACA, CATEGORIA, VALOR_DIARIA, STATUS) VALUES 
('Corolla', 'ABC-1234', 'Sedan', 180.00, 'disponivel'),
('Onix', 'DEF-5678', 'Hatch', 120.00, 'disponivel'),
('Compass', 'GHI-9012', 'SUV', 250.00, 'disponivel');

INSERT INTO ALUGA (
    FK_CLIENTE_ID_CLIENTE, FK_VEICULOS_ID_VEICULOS, 
    DATA_RETIRADA, DATA_PREVISTA, DATA_DEVOLUCAO, 
    DIAS_CONTRATADOS, DIAS_REAIS, 
    VALOR_BRUTO, DESCONTO, MULTA, VALOR_FINAL, STATUS
) VALUES 
(1, 1, '2026-05-05', '2026-05-10', '2026-05-10', 5, 5, 900.00, 45.00, 0.00, 855.00, 'Entregue'),
(2, 2, '2026-05-12', '2026-05-15', '2026-05-17', 3, 5, 600.00, 30.00, 72.00, 642.00, 'Atrasado'),
(3, 3, '2026-05-18', '2026-05-22', '2026-05-21', 4, 3, 1000.00, 100.00, 0.00, 900.00, 'Entregue Antecipado');